### PR TITLE
Additional parameters

### PR DESCRIPTION
**Pull request by iam-medvedev**
First of all, thanks for this module!

I added the ability to pass additional parameters to create cookies.

### CODE REVIEW

**Comment by xyzshantaram** [comment]
Thanks for your PR, this looks great!

**Comment by xyzshantaram** [comment]
@iam-medvedev I think we should move the cookie options to be in the call to init(), though, since that way it saves us from having to pass them to getClient every time; if they are left out by accident in one call, we'll have inconsistent cookie settings for different routes. Would love your opinion.

**Comment by iam-medvedev** [comment]
I agree. Passing parameters during initialization will be more consistent.

**Comment by iam-medvedev** [comment]
@xyzshantaram Could you please make a new release in deno.land? :)

**Comment by xyzshantaram** [comment]
Done!
Sorry for the delay.

**Pull request merged**
